---
- name: Install Requirements
  sudo: yes
  pip: name=gunicorn state=present

- name: Create gunicorn Upstart Job
  sudo: yes
  template: src=sfb.conf.j2 dest=/etc/init/sfb.conf

- name: Start gunicorn Upstart Job
  sudo: yes
  service: name=sfb state=restarted
