---
- name: Configure Common Tasks
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Configure Security Groups
      # these are wide open at the moment,
      # I was trying to sort something out with celery/sqs
      ec2_group:
        name: "{{ item.name }}"
        description: Security group for SFB demo.
        region: "{{ region }}"
        state: present
        rules: "{{ item.rules }}"
        rules_egress: "{{ item.rules_egress }}"
      with_items: security_groups
