---
- name: Configure Common Tasks
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: Configure Security Groups
      ec2_group:
        name: "{{ item.name }}"
        description: Security group for LAMP stack demo.
        region: "{{ region }}"
        state: present
        rules: "{{ item.rules }}"
        rules_egress: "{{ item.rules_egress }}"
      with_items: security_groups

    - name: make vpc
      ec2_vpc:
        state: present
        cidr_block: 172.23.0.0/16
        resource_tags: { "Environment":"Development" }
        region: us-west-2
      register: vpc

    - name: inspect vpc
      debug: msg="{{ vpc }}"

