---
- name: Provision Load Balancer
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:

    - name: Configure Elastic Load Balancers
      local_action:
        module: ec2_elb_lb
        region: "{{ region }}"
        name: sfb-lb
        state: present
        zones: "{{ zones }}"
        connection_draining_timeout: 60
        listeners:
          - protocol: http
            load_balancer_port: 80
            instance_port: 80
        health_check:
          ping_protocol: http
          ping_port: 80
          ping_path: "/"
          response_timeout: 5
          interval: 30
          unhealthy_threshold: 10
          healthy_threshold: 2
      register: elb

    - name: asdf
      set_fact:
        elb_dns_name: "{{ elb.elb.dns_name }}"
