---
- name: Provision EC2 Instances
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:

    - name: Provision EC2 Instances
      ec2:
        key_name: "{{ ssh_key }}"
        group: "{{ security_group }}"
        instance_type: "{{ instance_type }}"
        image: "{{ ami_id }}"
        region: "{{ region }}"
        wait: true
        exact_count: 1
        count_tag:
          Name: "{{ tag_Name }}"
        instance_tags:
          Name: "{{ tag_Name }}"
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: tag_Name_sfb-temp
        ec2_id: "{{ item.id }}"
      with_items: ec2.instances

    - name: Wait for SSH to come up
      wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances
