---
- name: Provision RDS Instance
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:

    #
    # couldn't get the security groups sorted out, so RDS is not provisioned
    # it connects to a DB that already exists.
    #

    - name: Provision MySQL Database
      rds:
        command: create
        instance_name: "{{ db_instance_name }}"
        db_engine: MySQL
        size: 5
        instance_type: "{{ db_instance_type }}"
        region: "{{ region }}"
        security_group: "{{ db_security_group }}"
        wait: yes
        wait_timeout: 600
        db_name: "{{ db_name }}"
        username: "{{ db_username }}"
        password: "{{ db_password }}"
        tags:
          Name: "{{ tag_Name }}"
      register: rds

    - name: save db endpoint and port info
      set_fact:
        db_endpoint: "{{ rds.instance.endpoint }}"
        db_port: "{{ rds.instance.port }}"
        db_url: "mysql://{{ rds.instance.username }}:{{ db_password }}@{{ rds.instance.endpoint }}:{{ rds.instance.port }}/{{ db_name }}"

    #- name: Provision Read Replica
