---
ssh_key: pk-aws
instance_type: t2.micro
db_instance_type: db.t2.micro
db_instance_name: sfb-demo
ami_id: ami-5189a661
region: us-west-2
tag_Name: sfb-demo

security_group: ssh-access
db_security_group: ssh-access

security_groups:
  - name: lamp_django
    rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: all
        from_port: 0
        to_port: 65535
        cidr_ip: 0.0.0.0/0
  - name: lamp_mysql
    rules:
      - proto: tcp
        from_port: 3306
        to_port: 3306
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: all
        from_port: 0
        to_port: 65535
        cidr_ip: 0.0.0.0/0

